### ISSUE TITLE
Upgrade Kafka and Confluent dependencies

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/schemas#13]
There are new versions of the dependencies from both the Kafka and Confluent (2.2.1 and 5.2.1 respectively, as of right now).

We should keep our dependencies up to date anyways, but especially because clients of these schemas libraries may not be able to use those updated dependencies themselves until we do here as well.

Tasks:
- [x] Upgrade Kafka and Confluent dependencies

**Comment by Ghebrechristos** [comment]
may be pass version as param so it is easier to change the version in one place 
${kafka-version}
${Confluent-version}
